app: go_service
mode: debug #debug release test
port: 10000

# 数据库配置
database:
  default: #默认配置
    host: 127.0.0.1
    port: 3306
    user: root
    pwd: 123456
    name: test
    maxIdle: 10
    maxOpen: 100
