# 应用配置
app:
  name: go_service
  mode: debug # debug, release, test
  version: 1.0.0
  environment: development # development, production, testing

# 服务器配置
server:
  host: 127.0.0.1
  port: 10000
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

# 数据库配置
database:
  default:
    host: 127.0.0.1
    port: 3306
    user: root
    pwd: 123456
    name: go_service
    maxIdle: 10
    maxOpen: 100
    maxLifetime: 1h
    connMaxIdleTime: 10m

# 日志配置
log:
  level: info # debug, info, warn, error
  format: json # json, text
  output: stdout # stdout, file
  max_size: 100 # MB
  max_backups: 3
  max_age: 28 # days
  compress: true

# 监控配置
monitor:
  enabled: true
  health_check_path: /health
  metrics_path: /metrics
  check_interval: 30s
  timeout: 10s
  retention_days: 7
  alert_webhook: "" # 告警webhook地址

# 安全配置
security:
  enable_auth: false
  jwt_secret: "your-jwt-secret-key"
  token_expiry: 24h
  rate_limit_enabled: true
  rate_limit_rps: 100
  allowed_ips: [] # 允许访问的IP列表，空表示允许所有
  tls_enabled: false
  cert_file: ""
  key_file: ""
